# ai_hydra/constants/DHydraTui.py
#
#    AI Hydra
#    Author: Nadim-Daniel Ghaznavi
#    Copyright: (c) 2025-2026 Nadim-Daniel Ghaznavi
#    GitHub: https://github.com/NadimGhaznavi/ai_hydra
#    Website: https://ai-hydra.readthedocs.io/en/latest
#    License: GPL 3.0

from typing import Final


class DColor:
    """Color constants"""

    BLACK: Final[str] = "black"
    BLUE: Final[str] = "blue"
    DARK_RED: Final[str] = "dark_red"
    GREEN: Final[str] = "green"
    PURPLE: Final[str] = "purple"
    RED: Final[str] = "red"
    WHITE: Final[str] = "white"
    YELLOW: Final[str] = "yellow"


class DField:
    """
    Machine readable field names.
    """

    ALL: Final[str] = "all"
    ATH_Memory: Final[str] = "ath_memory"
    BAD_HANDSHAKE: Final[str] = "bad_handshake"
    BATCH_SIZE: Final[str] = "batch_size"
    BATCH_SIZE_INPUT: Final[str] = "batch_size_input"
    BATCH_SIZE_LABEL: Final[str] = "batch_size_label"
    BLANK: Final[str] = "blank"
    BOARD_BOX: Final[str] = "board_box"
    BOTH: Final[str] = "both"
    BUTTONS: Final[str] = "buttons"
    CLIENTS: Final[str] = "clients"
    CLIENTS_SCREEN: Final[str] = "clients_screen"
    CLOSER_TO_FOOD_INPUT: Final[str] = "closer_to_food_input"
    CLOSER_TO_FOOD_LABEL: Final[str] = "closer_to_food_label"
    CONFIG: Final[str] = "config"
    CONSOLE_BOX: Final[str] = "console_box"
    CPU: Final[str] = "cpu"
    DISCONNECTED: Final[str] = "disconnected"
    COLLISION_PENALTY_INPUT: Final[str] = "collision_penalty_input"
    COLLISION_PENALTY_LABEL: Final[str] = "collision_penalty_label"
    CONSOLE: Final[str] = "console"
    CONSOLE_SCREEN: Final[str] = "console_screen"
    COUNT: Final[str] = "count"
    CUDA: Final[str] = "cuda"
    CUR_EPSILON: Final[str] = "cur_epsilon"
    CUR_LOSS: Final[str] = "cur_loss"
    DROPOUT_P: Final[str] = "dropout_p"
    DROPOUT_P_INPUT: Final[str] = "dropout_p_input"
    DROPOUT_P_LABEL: Final[str] = "dropout_p_label"
    DOWNSHIFT_COUNT_THRESHOLD_INPUT: Final[str] = (
        "downshift_count_thresh_input"
    )
    DOWNSHIFT_COUNT_THRESHOLD_LABEL: Final[str] = (
        "downshift_count_thresh_label"
    )
    EMPTY_MOVE_REWARD_INPUT: Final[str] = "empty_move_reward_input"
    EMPTY_MOVE_REWARD_LABEL: Final[str] = "empty_move_reward_label"
    EPSILON_BOX: Final[str] = "epsilon_box"
    EPSILON_DECAY: Final[str] = "epsilon_decay"
    EPSILON_DECAY_INPUT: Final[str] = "epsilon_decay_input"
    EPSILON_DECAY_LABEL: Final[str] = "epsilon_decay_label"
    EPSILON_DEPLETED: Final[str] = "epsilon_depleted"
    EPISODE_CONSTRAINTS_BOX: Final[str] = "episode_constraints_box"
    EVENT_LOG: Final[str] = "event_log"
    EVENT_LOG_LOG: Final[str] = "event_log_log"
    EVENTS: Final[str] = "events"
    FOOD_REWARD_INPUT: Final[str] = "food_reward_input"
    FOOD_REWARD_LABEL: Final[str] = "food_reward_label"
    FURTHER_FROM_FOOD_INPUT: Final[str] = "further_from_food_input"
    FURTHER_FROM_FOOD_LABEL: Final[str] = "further_from_food_label"
    GEAR: Final[str] = "gear"
    GAMMA_INPUT: Final[str] = "gamma_input"
    GAMMA_LABEL: Final[str] = "gamma_label"
    GAME_SCORE_PLOT: Final[str] = "game_score_plot"
    GAME_SCORES: Final[str] = "game_scores"
    GRU: Final[str] = "gru"
    HANDSHAKE: Final[str] = "handshake"
    HANDSHAKE_DIVIDER: Final[str] = "handshake_divider"
    HIDDEN_SIZE_INPUT: Final[str] = "hidden_size_input"
    HIDDEN_SIZE_LABEL: Final[str] = "hidden_size_label"
    HIDDEN_WIDGET: Final[str] = "hidden_widget"
    HIGHSCORE: Final[str] = "highscore"
    HIGHSCORES: Final[str] = "highscores"
    HIGHSCORES_BOX: Final[str] = "highscores_box"
    HIGHSCORES_LOG: Final[str] = "highscores_log"
    HIGHSCORES_PLOT: Final[str] = "highscores_plot"
    HIGHSCORES_LH: Final[str] = "highscores_lh"
    HYDRA_TELEMETRY: Final[str] = "hydra_telemetry"
    INITIAL_EPSILON: Final[str] = "initial_epsilon"
    INITIAL_EPSILON_INPUT: Final[str] = "initial_epsilon_input"
    INITIAL_EPSILON_LABEL: Final[str] = "initial_epsilon_label"
    INPUT_FIELD: Final[str] = "input_field"
    INPUT_SIZE: Final[str] = "input_size"
    INTEGER: Final[str] = "integer"
    LEARNING_RATE_INPUT: Final[str] = "learning_rate_input"
    LEARNING_RATE_LABEL: Final[str] = "learning_rate_label"
    LINEAR: Final[str] = "linear"
    LOOKAHEAD_BOX: Final[str] = "lookahead_box"
    LOOKAHEAD_STATUS: Final[str] = "lookahead_status"
    LOOKAHEAD_P_VAL_INPUT: Final[str] = "lookahead_p_val_input"
    LOOKAHEAD_P_VAL_LABEL: Final[str] = "lookahead_p_val_label"
    LOOKAHEAD_SAMPLE_P_VALUE_LABEL: Final[str] = "lookahead_sample_p_val_label"
    LOSS: Final[str] = "loss"
    LOSS_PLOT: Final[str] = "loss_plot"
    MAX_BUCKETS_INPUT: Final[str] = "max_buckets_input"
    MAX_BUCKETS_LABEL: Final[str] = "max_buckets_label"
    MAX_FRAMES_INPUT: Final[str] = "max_frames_input"
    MAX_FRAMES_LABEL: Final[str] = "max_frames_label"
    MAX_GEAR_INPUT: Final[str] = "max_gear_input"
    MAX_GEAR_LABEL: Final[str] = "max_gear_label"
    MAX_CRIT_STAGNANT_EPISODES_INPUT: Final[str] = "max_crit_stag_eps_input"
    MAX_CRIT_STAGNANT_EPISODES_LABEL: Final[str] = "max_crit_stag_eps_label"
    MAX_MOVES_MULTIPLIER_INPUT: Final[str] = "max_moves_multiplier_input"
    MAX_MOVES_MULTIPLIER_LABEL: Final[str] = "max_moves_multiplier_label"
    MAX_MOVES_PENALTY_INPUT: Final[str] = "max_moves_penalty_input"
    MAX_MOVES_PENALTY_LABEL: Final[str] = "max_moves_penalty_label"
    MAX_STAGNANT_EPISODES_INPUT: Final[str] = "max_stag_eps_input"
    MAX_STAGNANT_EPISODES_LABEL: Final[str] = "max_stag_eps_label"
    MAX_TRAINING_FRAMES_INPUT: Final[str] = "max_training_frames_input"
    MAX_TRAINING_FRAMES_LABEL: Final[str] = "max_training_frames_label"
    MEAN_SCORES_PLOT: Final[str] = "mean_scores_plot"
    MEM_SIZING_BOX: Final[str] = "mem_sizing_box"
    MIN_EPSILON: Final[str] = "min_epsilon"
    MIN_EPSILON_INPUT: Final[str] = "min_epsilon_input"
    MIN_EPSILON_LABEL: Final[str] = "min_epsilon_label"
    MODEL_BOX: Final[str] = "model_box"
    MODEL_TYPE_LABEL: Final[str] = "model_type_label"
    MODEL_TYPE_SELECT: Final[str] = "model_type_select"
    MOVE_DELAY_BOX: Final[str] = "move_delay_box"
    MOVE_DELAY_LABEL: Final[str] = "move_delay_label"
    MOVE_DELAY_INPUT: Final[str] = "move_delay_input"
    MOVEMENT_INCENTIVES_BOX: Final[str] = "movement_incentives_box"
    MPS: Final[str] = "mps"
    NETWORK: Final[str] = "network"
    NICE_BOX: Final[str] = "nice_box"
    NICE_P_VALUE_INPUT: Final[str] = "nice_p_value_input"
    NICE_P_VALUE_LABEL: Final[str] = "nice_p_value_label"
    NICE_STEPS_INPUT: Final[str] = "nice_steps_input"
    NICE_STEPS_LABEL: Final[str] = "nice_steps_label"
    NORMAL: Final[str] = "normal"
    NUM_COOLDOWN_EPISODES_INPUT: Final[str] = "num_cooldown_eps_input"
    NUM_COOLDOWN_EPISODES_LABEL: Final[str] = "num_cooldown_eps_label"
    NUMBER: Final[str] = "number"
    PAUSE_RUN: Final[str] = "pause_run"
    PAUSE_RUN_DIVIDER: Final[str] = "pause_run_divider"
    PLOT_CUR_SCORE: Final[str] = "plot_cur_score"
    PLOT_HIGHSCORES: Final[str] = "plot_highscores"
    PLOT_LOSS: Final[str] = "plot_loss"
    PLOT_MEAN: Final[str] = "plot_mean"
    PLOT_RECENT_LOSS: Final[str] = "plot_recent_loss"
    PLOT_RECENT_MEAN: Final[str] = "plot_recent_mean"
    PLOT_RECENT_SCORES_DIST: Final[str] = "plot_recent_scores_dist"
    PLOT_SCORES_DIST: Final[str] = "plot_scores_dist"
    QUIT: Final[str] = "quit"
    RECENT: Final[str] = "recent"
    REPLAY_MEM: Final[str] = "replay_mem"
    RANDOM_SEED_BOX: Final[str] = "random_seed_box"
    RANDOM_SEED_INPUT: Final[str] = "random_seed_input"
    RANDOM_SEED_LABEL: Final[str] = "random_seed_label"
    RESET: Final[str] = "reset"
    RESET_RUN: Final[str] = "reset_run"
    RESET_RUN_DIVIDER: Final[str] = "reset_run_divider"
    RESUME_RUN: Final[str] = "resume_run"
    RESUME_RUN_DIVIDER: Final[str] = "resume_run_divider"
    REWARD_STRUCTURE_BOX: Final[str] = "reward_structure_box"
    RNN: Final[str] = "rnn"
    RNN_BATCH_SIZE_LABEL: Final[str] = "rnn_batch_size_label"
    RNN_TAU_INPUT: Final[str] = "rnn_tau_input"
    RNN_TAU_LABEL: Final[str] = "rnn_tau_label"
    RNN_TAU_OPT: Final[str] = "rnn_tau_opt"
    RNN_LAYERS_INPUT: Final[str] = "rnn_layers_input"
    RNN_LAYERS_LABEL: Final[str] = "rnn_layers_label"
    RNN_LAYERS_OPT: Final[str] = "rnn_layers_opt"
    RNN_DROPOUT: Final[str] = "rnn_dropout"
    RNN_LAYERS: Final[str] = "rnn_layers"
    ROUTER_BOX: Final[str] = "router_box"
    ROUTER_ADDR: Final[str] = "router_addr"
    ROUTER_PORT: Final[str] = "router_port"
    ROUTER_HB_PORT: Final[str] = "router_hb_port"
    ROUTER_HB_STATUS: Final[str] = "router_hb_status"
    RUNNING: Final[str] = "running"
    SCORES_DIST_PLOT: Final[str] = "scores_list_plot"
    SEQ_LENGTH: Final[str] = "seq_length"
    SERVER_ADDR: Final[str] = "server_addr"
    SERVER_BOX: Final[str] = "server_box"
    SERVER_PUB_PORT: Final[str] = "server_pub_port"
    SERVER_STATUS: Final[str] = "server_status"
    SETTINGS: Final[str] = "settings"
    SEQ_LENGTH_INPUT: Final[str] = "seq_length_input"
    SEQ_LENGTH_LABEL: Final[str] = "seq_length_label"
    SEQ_LENGTH_OPT: Final[str] = "seq_length_opt"
    SCORES_PLOT: Final[str] = "scores_plot"
    SCORES_PLOT_LH: Final[str] = "scores_plot_lh"
    SCORES_PLOT_NLH: Final[str] = "scores_plot_nlh"
    SCORES_SCATTER_PLOT: Final[str] = "scores_scatter_plot"
    SHIFTING_BOX: Final[str] = "shifting_box"
    SIM_LOOP: Final[str] = "sim_loop"
    SIM_PAUSED: Final[str] = "sim_paused"
    SIM_RUNNING: Final[str] = "sim_running"
    SIM_STOPPED: Final[str] = "sim_stopped"
    SNAPSHOT: Final[str] = "snapshot"
    SNAPSHOT_DIVIDER: Final[str] = "snapshot_divider"
    STAGNATION_BOX: Final[str] = "stagnation_box"
    STATS_WINDOW: Final[str] = "stats_window"
    STATUS: Final[str] = "status"
    START: Final[str] = "start"
    START_RUN: Final[str] = "start_run"
    START_RUN_DIVIDER: Final[str] = "start_run_divider"
    STOP: Final[str] = "stop"
    STOPPED: Final[str] = "stopped"
    TABBED_PLOTS: Final[str] = "tabbed_plots"
    TABBED_SETTINGS: Final[str] = "tabbed_settings"
    TANH: Final[str] = "tanh"
    TITLE: Final[str] = "title"
    TRAINING_BOX: Final[str] = "training_box"
    TUI: Final[str] = "tui"
    TURBO_BOX: Final[str] = "turbo_box"
    TURBO_MODE: Final[str] = "turbo_mode"
    TURBO_OFF: Final[str] = "turbo_off"
    TURBO_ON: Final[str] = "turbo_on"
    UPDATE_RUNTIME_CONFIG: Final[str] = "update_runtime_config"
    UPDATE_CONFIG_SPACER: Final[str] = "update_config_spacer"
    UPSHIFT_COUNT_THRESHOLD_LABEL: Final[str] = "upshift_count_threshold_label"
    UPSHIFT_COUNT_THRESHOLD_INPUT: Final[str] = "upshift_count_threshold_input"
    WARNING: Final[str] = "warning"


class DFile:
    """
    Filenames.
    """

    CLIENT_CSS: Final[str] = "HydraClient.tcss"
    ROUTER_CSS: Final[str] = "HydraRouter.tcss"
    HYDRA_SERVER_DB: Final[str] = "HydraServer.db"
    BASE_SNAPSHOT: Final[str] = "AI-Hydra-Snapshot_"


class DLabel:
    """
    Human readable text.
    """

    ACTIONS: Final[str] = "Actions"
    AVERAGE: Final[str] = "Average"
    BATCH_SIZE: Final[str] = "Batch Size"
    BOTH: Final[str] = "Both"
    CLIENT_TITLE: Final[str] = "Hydra Client"
    CLIENTS: Final[str] = "Clients"
    CLOSER_TO_FOOD: Final[str] = "Closer to Food"
    COLLISION_PENALTY: Final[str] = "Collision Penalty"
    COMPLETE: Final[str] = "Complete"
    CONFIG: Final[str] = "Config"
    CONSOLE: Final[str] = "Console"
    COUNT: Final[str] = "Count"
    CUR_LOSS: Final[str] = "Current Loss"
    CUR_EPSILON: Final[str] = "Current Epsilon"
    CURRENT: Final[str] = "Current"
    CUR_SCORES: Final[str] = "Current Scores"
    DEBUG: Final[str] = "DEBUG"
    DISCONNECTED: Final[str] = "Disonnected"
    DROPOUT_P_VAL: Final[str] = "Dropout P-Value"
    DOWNSHIFT_COUNT_THRESHOLD: Final[str] = "Downshift Threshold"
    EMPTY_MOVE_REWARD: Final[str] = "Empty Move Reward"
    EPISODE: Final[str] = "Episode"
    EPISODES: Final[str] = "Episodes"
    EPSILON: Final[str] = "Epsilon"
    EPSILON_DECAY: Final[str] = "Epsilon Decay"
    EPSILON_NICE: Final[str] = "Epsilon Nice"
    ERROR: Final[str] = "ERROR"
    EPISODE_CONSTRAINTS: Final[str] = "Episode Constraints"
    EVENT: Final[str] = "Event"
    EVENT_LOG: Final[str] = "Event Log"
    EVENT_TIME: Final[str] = "Event"
    FOOD_REWARD: Final[str] = "Food Reward"
    FURTHER_FROM_FOOD: Final[str] = "Further from Food"
    GAME: Final[str] = "Game"
    GAME_SCORES: Final[str] = "Game Scores"
    GAMMA: Final[str] = "Discount/Gamma"
    GRU: Final[str] = "GRU"
    HANDSHAKE: Final[str] = "Handshake"
    HEARTBEAT_PORT: Final[str] = "Heartbeat Port"
    HIDDEN_SIZE: Final[str] = "Hidden Size"
    HIGHSCORE: Final[str] = "Highscore"
    HIGHSCORES: Final[str] = "Highscores"
    HIGHSCORES_LH: Final[str] = "Look Ahead"
    INITIAL_EPSILON: Final[str] = "Initial Epsilon"
    LEFT: Final[str] = "Left"
    LH: Final[str] = "LA"
    LEARNING_RATE: Final[str] = "Learning Rate"
    LINEAR: Final[str] = "Linear"
    LISTEN_PORT: Final[str] = "Listening Port"
    LOOKAHEAD: Final[str] = "Look Ahead"
    LOOKAHEAD_SETTINGS: Final[str] = "Look Ahead Settings"
    LOSS: Final[str] = "Loss"
    MAX_BUCKETS: Final[str] = "Memory Buckets"
    MAX_FRAMES: Final[str] = "Max Frames"
    MAX_GEAR: Final[str] = "Highest Gear"
    MAX_HARD_RESET_EPISODES: Final[str] = "Critical Threshold"
    MAX_MOVES_MULTIPLIER: Final[str] = "Max Moves Multiplier"
    MAX_MOVES_PENALTY: Final[str] = "Max Moves Penalty"
    MAX_STAGNANT_EPISODES: Final[str] = "Threshold"
    MAX_TRAINING_FRAMES: Final[str] = "Max Training Frames"
    MEAN: Final[str] = "Mean"
    MEAN_SCORES: Final[str] = "Mean Scores"
    MEMORY: Final[str] = "Memory"
    MEDIAN: Final[str] = "Median"
    MIN_EPSILON: Final[str] = "Minimum Epsilon"
    MODEL: Final[str] = "Model"
    MCTS: Final[str] = "Monte Carlo Tree Search"
    MCTS_EXPLORE_P_VALUE: Final[str] = "Exploration P-Value"
    MCTS_GATE_P_VALUE: Final[str] = "Gating P-Value"
    MCTS_ITER: Final[str] = "Iterations"
    MCTS_SCORE_THRESH: Final[str] = "Score Threshold"
    MOVE_DELAY: Final[str] = "Move Delay"
    MOVEMENT_INCENTIVES: Final[str] = "Movement Incentives"
    NETWORK: Final[str] = "Network"
    NICE: Final[str] = "Nice"
    NICE_P_VALUE: Final[str] = "Nice P-Value"
    NICE_STEPS: Final[str] = "Nice Steps"
    NN_MODEL: Final[str] = "NN Model"
    NORMAL: Final[str] = "Normal"
    NUM_COOLDOWN_EPISODES: Final[str] = "Cooldown Threshold"
    P_VALUE: Final[str] = "P-Value"
    PAUSE: Final[str] = "Pause"
    PING_ROUTER: Final[str] = "Ping Router"
    PING_SERVER: Final[str] = "Ping Server"
    POLICY: Final[str] = "Policy"
    QUIT: Final[str] = "Quit"
    RANDOM_SEED: Final[str] = "Random Seed"
    RECENT_COUNT: Final[str] = "Recent Scores"
    RECENT_LOSS: Final[str] = "Recent Loss"
    RECENT_MEAN: Final[str] = "Recent Mean"
    RECENT_MEANS: Final[str] = "Recent Means"
    RESET: Final[str] = "Reset"
    RESUME: Final[str] = "Resume"
    REWARD_STRUCTURE: Final[str] = "Reward Structure"
    REWARDS: Final[str] = "Rewards"
    RIGHT: Final[str] = "Right"
    RNN: Final[str] = "RNN"
    RNN_LAYERS: Final[str] = "Layers"
    RNN_TAU: Final[str] = "Tau"
    ROUTER: Final[str] = "Router"
    ROUTER_ADDR: Final[str] = "Address"
    ROUTER_HB_PORT: Final[str] = "Heartbeat Port"
    ROUTER_PORT: Final[str] = "Control Port"
    ROUTER_STATUS: Final[str] = "Status"
    ROUTER_TITLE: Final[str] = "Hydra Router"
    SEARCH_DEPTH: Final[str] = "Search Depth"
    SETTINGS: Final[str] = "Settings"
    SAMPLING_P_VALUE: Final[str] = "Sampling P-Value"
    SCORE: Final[str] = "Score"
    SCORE_DISTRIBUTION: Final[str] = "Score Distribution"
    SCORES: Final[str] = "Scores"
    SCORES_ALL: Final[str] = "Scores/All"
    SCORES_LH: Final[str] = "Scores/L.A."
    SCORES_NLH: Final[str] = "Scores/No L.A."
    SCORES_SCATTER: Final[str] = "Scores Scatterplot"
    SEQUENCE_LENGTH: Final[str] = "Sequence Length"
    SERVER: Final[str] = "Hydra Manager"
    SERVER_ADDR: Final[str] = "Address"
    SERVER_PUB_PORT: Final[str] = "ZMQ PUB Port"
    SERVER_STATUS: Final[str] = "Status"
    SHIFTING: Final[str] = "Gearbox Settings"
    SIZING: Final[str] = "Memory Sizing"
    SNAPSHOT: Final[str] = "Snapshot"
    SPACE: Final[str] = " "
    STAGNATION: Final[str] = "Stagnation Thresholds"
    START: Final[str] = "Start"
    STATUS: Final[str] = "Status"
    STEPS: Final[str] = "Steps"
    STOP: Final[str] = "Stop"
    STATUS: Final[str] = "Status"
    STRAIGHT: Final[str] = "Straight"
    TIME: Final[str] = "Time"
    TRAINING: Final[str] = "Training"
    TURBO_MODE: Final[str] = "Turbo Mode"
    TYPE: Final[str] = "Type"
    UPDATE_CONFIG: Final[str] = "Update Config"
    UPSHIFT_COUNT_THRESHOLD: Final[str] = "Upshift Threshold"
    VERSION: Final[str] = "Version"
    VISUALIZATIONS: Final[str] = "Visualizations"


class DPlotDef:
    """
    Default Textual plot settings.
    """

    # The average is calculated by dividing the MAX_DATA_POINTS by this number
    AVG_DIVISOR: int = 50

    MAX_LOSS_DATA_POINTS: Final[int] = 125
    MAX_CUR_DATA_POINTS: Final[int] = 200
    MAX_CUR_LOSS_DATA_POINTS: Final[int] = 90

    # GameScorePlot widget settings
    MAX_GAMES = 75
    MAX_GAMES_AVG_DIVISOR: int = 50

    # Maximum number of scores stored in the metrics object
    MAX_CUR_SCORES = 150

    # The number of "recent" games in the mean scores plot
    RECENT_MEAN_MAX = 100

    # The number of mean data points in the "Mean Scores" plot
    MAX_MEAN_DATA_POINTS = 100
    MAX_RECENT_MEAN_DATA_POINTS = 125

    # The number of "recent" games in the score distribution histogram
    RECENT_SCORES_MAX = 500

    # The number of "recent" loss data points in the "Recent Loss" plot
    RECENT_LOSS_MAX = 75


class DStatus:
    """
    Status indicators.
    """

    GOOD: Final[str] = "🟢"
    ON: Final[str] = "🟢"
    OK: Final[str] = "🟡"
    BAD: Final[str] = "🔴"
    OFF: Final[str] = "🔴"
    UNKNOWN: Final[str] = "⚪"
