from typing import Any

class RequestException(Exception): ...

class Response:
    status_code: int
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...
    def iter_lines(self) -> Any: ...

class Session:
    def get(self, *args: Any, **kwargs: Any) -> Response: ...
